# Generated by Django 4.2.5 on 2023-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
