# Generated by Django 4.2.5 on 2023-10-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_recordingsession_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingchunk',
            name='file_path',
            field=models.CharField(max_length=512),
        ),
    ]
